# Generated by Django 3.0.8 on 2020-07-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
